### ISSUE TITLE
How to generate those image?

### ISSUE THREAD

**Issue by StevenLOL** [pannous/caffe-speech-recognition#3]
Need go home now, you can point me to the file , I can help you to write some docs.

**Comment by JoshuaBatty** [comment]
Hey I am having a problem running this script. I've managed to have all the included libraries working and now the script runs but im getting the below error. Any idea why it gets stuck in the IOError? @StevenLOL did you get this script to work at all? anyone? 

![audio-fft error](https://cloud.githubusercontent.com/assets/1289413/9054881/fb5a7d60-3ac8-11e5-91ab-b1ac53c721dd.png)

**Comment by StevenLOL** [comment]
Hi, @JoshuaBatty , sorry for the late reply. I didn't generate image by audio-fft.py , instead I use matlab to writ images. 

Now I am thinking save features as image for speech task may not a good idea, as there is a information lost during conversion.
