### ISSUE TITLE
Any idea on how to deploy it ?

### ISSUE THREAD

**Issue by StevenLOL** [pannous/caffe-speech-recognition#4]
To say I have the trained model, and would like to run a testcase, maybe just on the test_index.txt ?

**Comment by Mingcong** [comment]
I have got the trained model by running the script. Could you provide an example to recognize the numbers from audio file?

**Comment by pannous** [comment]
yes, doku README.md updated

**Comment by StevenLOL** [comment]
Thanks ,FYI

Here is another free corpus

LibriSpeech: an ASR corpus based on public domain audio books

http://www.danielpovey.com/files/2015_icassp_librispeech.pdf

By Dan Povey, the core developer of the state of art ASR system: (Kaldi)[http://kaldi.sourceforge.net/]

They provide sets of examples in their ./egs folder on different corpus, some of them are free of charge.
