### ISSUE TITLE
broken link http://pannous.net/spoken_words.tar

### ISSUE THREAD

**Issue by StevenLOL** [pannous/caffe-speech-recognition#5]
Hi, there is a broken link

http://pannous.net/spoken_words.tar

**Comment by ricyoung** [comment]
that link is broken also

**Comment by zkailinzhang** [comment]
hello，the speech dataset link is expired，could you share a valid link?

**Comment by pannous** [comment]
try http://pannous.com/wp-content/spoken_words.tar
keep in mind that this project is deprecated and should only be used for educational purposes, if at all.

**Comment by NyxRockchip2017** [comment]
that link is broken also
