### ISSUE TITLE
File not found: numbers_iter.solverstate ...?

### ISSUE THREAD

**Issue by JoshuaBatty** [pannous/caffe-speech-recognition#7]
Hey pannous, feel like im finally getting close to getting this to work but the train.sh script is failing a the very end because it can't find the numbers_iter.solverstate file. I can't seem to find a reference to it anywhere on my computer or online anywhere. Would you be able to describe what i'm doing wrong? Thanks. 

Check failed: fd != -1 (-1 vs. -1) File not found: numbers_iter.solverstate
*** Check failure stack trace: ***
    @        0x10efb4448  google::LogMessage::Fail()
    @        0x10efb3bf4  google::LogMessage::SendToLog()
    @        0x10efb40a2  google::LogMessage::Flush()
    @        0x10efb74ed  google::LogMessageFatal::~LogMessageFatal()
    @        0x10efb4753  google::LogMessageFatal::~LogMessageFatal()
    @        0x10a2af648  caffe::ReadProtoFromBinaryFile()
    @        0x10a29b1b5  caffe::Solver<>::Restore()
    @        0x10a29afa6  caffe::Solver<>::Solve()
    @        0x10a17f59d  train()
    @        0x10a18181f  main
    @     0x7fff985f95c9  start
    @                0x7  (unknown)
./train.sh: line 1:  1760 Abort trap: 6           ../../caffe/build/tools/caffe train -solver numbers_solver.prototxt -gpu 0 --snapshot=numbers_iter.solverstate

**Comment by pannous** [comment]
sorry, fixed
 #--snapshot=numbers_iter.solverstate

**Comment by JoshuaBatty** [comment]
Thanks!
